name: Lighthouse CI

on:
  # 1) プルリクエスト時に計測 → コード変更がサイトを重くしていないかチェック
  pull_request:
    branches: [ "main" ]

  # 2) 毎日深夜（UTCで16時は日本時間で翌1時）に定期実行
  schedule:
    - cron: "0 16 * * *"

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli

      # 必要であればビルド処理、デプロイ前計測など
      # - name: Build project (if needed)
      #   run: npm run build

      - name: Run Lighthouse CI
        id: lhci
        run: |
          lhci autorun \
            --config=./lighthouserc.json \
            --upload.target=temporary-public-storage

      - name: Notify Slack on failure
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": ":warning: Lighthouse CIでスコアが閾値未満のページが検出されました。詳細: https://github.com/ORG/REPO/actions"
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
