name: Lighthouse CI

on:
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 16 * * *"  # 毎日1時(JST)に定期実行

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli

      - name: Run Lighthouse CI
        id: lhci
        run: |
          lhci autorun \
            --config=./lighthouserc.json \
            --upload.target=temporary-public-storage

      # ★ここがSlack連携部分★
      - name: Notify Slack on failure
        if: failure()  # Lighthouse CIでエラー（閾値未達）がある場合のみ実行
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": ":warning: Lighthouse CIでパフォーマンススコアが閾値未満のページが検出されました。詳細ログはActions画面を確認してください。"
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
